package com.application.entities;

import android.os.Parcel;
import android.os.Parcelable;

public class PackageTrip implements Parcelable {

    private String id;
    private String nome;
    private String preco;
    private String descricao;
    private String viagemID;

    public PackageTrip(String id, String nome, String preco, String descricao, String viagemID) {
        this.id = id;
        this.nome = nome;
        this.preco = preco;
        this.descricao = descricao;
        this.viagemID = viagemID;
    }

    public PackageTrip() {
        //Must have a public no-argument constructor
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getPreco() {
        return preco;
    }

    public void setPreco(String preco) {
        this.preco = preco;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getViagemID() {
        return viagemID;
    }

    public void setViagemID(String viagemID) {
        this.viagemID = viagemID;
    }

    //Below it's everything needed to use Parcelable inmplementation
    //Needed in order to put object in a Bundle to be passed in an Intent
    //Generated by website parcelabler.com
    protected PackageTrip(Parcel in) {
        id = in.readString();
        nome = in.readString();
        preco = in.readString();
        descricao = in.readString();
        viagemID = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(nome);
        dest.writeString(preco);
        dest.writeString(descricao);
        dest.writeString(viagemID);
    }

    @SuppressWarnings("unused")
    public static final Parcelable.Creator<PackageTrip> CREATOR = new Parcelable.Creator<PackageTrip>() {
        @Override
        public PackageTrip createFromParcel(Parcel in) {
            return new PackageTrip(in);
        }

        @Override
        public PackageTrip[] newArray(int size) {
            return new PackageTrip[size];
        }
    };
}
