package com.application.entities;

import android.os.Parcel;
import android.os.Parcelable;

public class Passenger implements Parcelable {

    private String id;
    private String nome;
    private String identidade;
    private String tipoIdentidade;
    private String dataNascimento;
    private String telefone;
    private String endereco;

    public Passenger(String nome, String identidade, String tipoIdentidade, String dataNascimento, String telefone) {
        this.nome = nome;
        this.identidade = identidade;
        this.tipoIdentidade = tipoIdentidade;
        this.dataNascimento = dataNascimento;
        this.telefone = telefone;
    }


    public Passenger(String nome, String identidade, String tipoIdentidade, String dataNascimento, String telefone, String endereco) {
        this.nome = nome;
        this.identidade = identidade;
        this.tipoIdentidade = tipoIdentidade;
        this.dataNascimento = dataNascimento;
        this.telefone = telefone;
        this.endereco = endereco;
    }

    public Passenger() {
        //Must have a public no-argument constructor
    }

    public String getId() {
        return id;
    }

    public String getNome() {
        return nome;
    }

    public String getIdentidade() {
        return identidade;
    }

    public String getTipoIdentidade() {
        return tipoIdentidade;
    }

    public String getDataNascimento() {
        return dataNascimento;
    }

    public String getTelefone() {
        return telefone;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setId(String id) {
        this.id = id;
    }

    //Below it's everything needed to use Parcelable inmplementation
    //Needed in order to put object in a Bundle to be passed in an Intent
    //Generated by website parcelabler.com
    protected Passenger(Parcel in) {
        id = in.readString();
        nome = in.readString();
        identidade = in.readString();
        tipoIdentidade = in.readString();
        dataNascimento = in.readString();
        telefone = in.readString();
        endereco = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(nome);
        dest.writeString(identidade);
        dest.writeString(tipoIdentidade);
        dest.writeString(dataNascimento);
        dest.writeString(telefone);
        dest.writeString(endereco);
    }

    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Passenger> CREATOR = new Parcelable.Creator<Passenger>() {
        @Override
        public Passenger createFromParcel(Parcel in) {
            return new Passenger(in);
        }

        @Override
        public Passenger[] newArray(int size) {
            return new Passenger[size];
        }
    };
}
