package com.application.entities;

import android.os.Parcel;
import android.os.Parcelable;

public class Passenger implements Parcelable {

    private String id;
    private String nome;
    private String identidade;
    private String tipoIdentidade;
    private String dataNascimento;
    private String telefone;
    private String endereco;
    private String pasviagemId;
    private String pasviagemVeiculo;
    private String pasviagemAssento;
    private String pasviagemEmbarque;
    private String pasviagemDesembarque;
    private String pasviagemValorPago;

    public Passenger(String nome, String identidade, String tipoIdentidade, String dataNascimento, String telefone) {
        this.nome = nome;
        this.identidade = identidade;
        this.tipoIdentidade = tipoIdentidade;
        this.dataNascimento = dataNascimento;
        this.telefone = telefone;
    }


    public Passenger(String nome, String identidade, String tipoIdentidade, String dataNascimento, String telefone, String endereco) {
        this.nome = nome;
        this.identidade = identidade;
        this.tipoIdentidade = tipoIdentidade;
        this.dataNascimento = dataNascimento;
        this.telefone = telefone;
        this.endereco = endereco;
    }

    public Passenger() {
        //Must have a public no-argument constructor
    }

    public String getId() {
        return id;
    }

    public String getNome() {
        return nome;
    }

    public String getIdentidade() {
        return identidade;
    }

    public String getTipoIdentidade() {
        return tipoIdentidade;
    }

    public String getDataNascimento() {
        return dataNascimento;
    }

    public String getTelefone() {
        return telefone;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public void setIdentidade(String identidade) {
        this.identidade = identidade;
    }

    public void setTipoIdentidade(String tipoIdentidade) {
        this.tipoIdentidade = tipoIdentidade;
    }

    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    //Below it's everything needed to use Parcelable inmplementation
    //Needed in order to put object in a Bundle to be passed in an Intent
    //Generated by website parcelabler.com
    protected Passenger(Parcel in) {
        id = in.readString();
        nome = in.readString();
        identidade = in.readString();
        tipoIdentidade = in.readString();
        dataNascimento = in.readString();
        telefone = in.readString();
        endereco = in.readString();
        pasviagemId = in.readString();
        pasviagemVeiculo = in.readString();
        pasviagemAssento = in.readString();
        pasviagemEmbarque = in.readString();
        pasviagemDesembarque = in.readString();
        pasviagemValorPago = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(nome);
        dest.writeString(identidade);
        dest.writeString(tipoIdentidade);
        dest.writeString(dataNascimento);
        dest.writeString(telefone);
        dest.writeString(endereco);
        dest.writeString(pasviagemId);
        dest.writeString(pasviagemVeiculo);
        dest.writeString(pasviagemAssento);
        dest.writeString(pasviagemEmbarque);
        dest.writeString(pasviagemDesembarque);
        dest.writeString(pasviagemValorPago);
    }

    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Passenger> CREATOR = new Parcelable.Creator<Passenger>() {
        @Override
        public Passenger createFromParcel(Parcel in) {
            return new Passenger(in);
        }

        @Override
        public Passenger[] newArray(int size) {
            return new Passenger[size];
        }
    };

    public String getPasviagemId() {
        return pasviagemId;
    }

    public void setPasviagemId(String pasviagemId) {
        this.pasviagemId = pasviagemId;
    }

    public String getPasviagemVeiculo() {
        return pasviagemVeiculo;
    }

    public void setPasviagemVeiculo(String pasviagemVeiculo) {
        this.pasviagemVeiculo = pasviagemVeiculo;
    }

    public String getPasviagemAssento() {
        return pasviagemAssento;
    }

    public void setPasviagemAssento(String pasviagemAssento) {
        this.pasviagemAssento = pasviagemAssento;
    }

    public String getPasviagemEmbarque() {
        return pasviagemEmbarque;
    }

    public void setPasviagemEmbarque(String pasviagemEmbarque) {
        this.pasviagemEmbarque = pasviagemEmbarque;
    }

    public String getPasviagemDesembarque() {
        return pasviagemDesembarque;
    }

    public void setPasviagemDesembarque(String pasviagemDesembarque) {
        this.pasviagemDesembarque = pasviagemDesembarque;
    }

    public String getPasviagemValorPago() {
        return pasviagemValorPago;
    }

    public void setPasviagemValorPago(String pasviagemValorPago) {
        this.pasviagemValorPago = pasviagemValorPago;
    }
}
