package com.application.entities;

import android.os.Parcel;
import android.os.Parcelable;

public class Trip implements Parcelable {

    private String id;
    private String nome;
    private String destino;
    private String limite;
    private String valor;
    private String valor_arrecadado;
    private String partida_data;
    private String partida_hora;
    private String retorno_data;
    private String retorno_hora;

    public Trip(String nome, String destino, String limite, String valor, String valor_arrecadado, String partida_data, String partida_hora, String retorno_data, String retorno_hora) {
        this.nome = nome;
        this.destino = destino;
        this.limite = limite;
        this.valor = valor;
        this.valor_arrecadado = valor_arrecadado;
        this.partida_data = partida_data;
        this.partida_hora = partida_hora;
        this.retorno_data = retorno_data;
        this.retorno_hora = retorno_hora;
    }

    public Trip() {
        //Must have a public no-argument constructor
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }

    public String getLimite() {
        return limite;
    }

    public void setLimite(String limite) {
        this.limite = limite;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    public String getValor_arrecadado() {
        return valor_arrecadado;
    }

    public void setValor_arrecadado(String valor_arrecadado) {
        this.valor_arrecadado = valor_arrecadado;
    }

    public String getPartida_data() {
        return partida_data;
    }

    public void setPartida_data(String partida_data) {
        this.partida_data = partida_data;
    }

    public String getPartida_hora() {
        return partida_hora;
    }

    public void setPartida_hora(String partida_hora) {
        this.partida_hora = partida_hora;
    }

    public String getRetorno_data() {
        return retorno_data;
    }

    public void setRetorno_data(String retorno_data) {
        this.retorno_data = retorno_data;
    }

    public String getRetorno_hora() {
        return retorno_hora;
    }

    public void setRetorno_hora(String retorno_hora) {
        this.retorno_hora = retorno_hora;
    }

    //Below it's everything needed to use Parcelable inmplementation
    //Needed in order to put object in a Bundle to be passed in an Intent
    //Generated by website parcelabler.com
    protected Trip(Parcel in) {
        id = in.readString();
        nome = in.readString();
        destino = in.readString();
        limite = in.readString();
        valor = in.readString();
        valor_arrecadado = in.readString();
        partida_data = in.readString();
        partida_hora = in.readString();
        retorno_data = in.readString();
        retorno_hora = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(nome);
        dest.writeString(destino);
        dest.writeString(limite);
        dest.writeString(valor);
        dest.writeString(valor_arrecadado);
        dest.writeString(partida_data);
        dest.writeString(partida_hora);
        dest.writeString(retorno_data);
        dest.writeString(retorno_hora);
    }

    @SuppressWarnings("unused")
    public static final Parcelable.Creator<Trip> CREATOR = new Parcelable.Creator<Trip>() {
        @Override
        public Trip createFromParcel(Parcel in) {
            return new Trip(in);
        }

        @Override
        public Trip[] newArray(int size) {
            return new Trip[size];
        }
    };
}
